-- seed.sql
-- CustomWebService seed data
-- 프로덕션 api_catalog 미러 (2026-06-22 전면 재동기화 — 잔여작업 B-5)
-- 총 49개 API + 7개 피처 플래그
--
-- ⚠️ 이 파일은 프로덕션 Supabase(custom-web-service) api_catalog를 그대로 미러링한다.
--    각 INSERT 위 주석의 [active=...]가 실제 활성 여부다. is_active=false 행은 플랫폼 키
--    미설정 또는 폐기(deprecated)로 비활성이며, 신규 환경에서도 비활성으로 시드된다.
--    재동기화: 프로덕션 api_catalog를 format()으로 덤프해 이 파일을 재생성한다
--    (docs/decisions/2026-06-22-catalog-registration-and-seed-resync.md 참조).
--
-- 사용법: Supabase SQL Editor에서 이 파일 전체를 실행하세요.
-- 신규(빈) 환경에서는 DELETE가 전체를 비우고 깨끗하게 재삽입한다.

-- ============================================================
-- FEATURE FLAGS
-- ============================================================

INSERT INTO feature_flags (flag_name, enabled, description, rules) VALUES
  ('enable_dark_mode', true, 'Enable dark mode UI theme toggle', '{"default": true}'::jsonb),
  ('enable_code_viewer', true, 'Enable the code viewer panel for generated output', '{"default": true}'::jsonb),
  ('enable_ollama_fallback', false, 'Fall back to local Ollama models when cloud AI is unavailable', '{"models": ["llama3", "codellama"]}'::jsonb),
  ('enable_template_system', false, 'Enable project templates for quick start', '{"categories": ["dashboard", "landing", "widget"]}'::jsonb),
  ('enable_multi_language', false, 'Enable multi-language UI support (i18n)', '{"supported": ["ko", "en", "ja"]}'::jsonb),
  ('enable_team_features', false, 'Enable team collaboration and organization features', '{"min_plan": "pro"}'::jsonb),
  ('enable_advanced_prompt', false, 'Enable advanced prompt engineering options for code generation', '{"max_tokens": 4096}'::jsonb)
ON CONFLICT (flag_name) DO NOTHING;

-- ============================================================
-- API CATALOG (프로덕션 미러 — category 순 정렬, 활성 우선)
-- ============================================================
-- 기존 데이터 정리 후 새로 삽입 (project_apis FK 참조가 없는 항목만 삭제)
DELETE FROM api_catalog WHERE id NOT IN (SELECT DISTINCT api_id FROM project_apis);

-- Countries (Self-hosted)  [data, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Countries (Self-hosted)', '250개 나라의 수도, 지역, 국기, 언어, 통화, 국가번호, 면적 정보를 제공해요. REST Countries 대체 API로, 가입·키 없이 바로 사용할 수 있어요.', 'data', 'https://xzawed.xyz', 'none', NULL, NULL, true, NULL, '[{"path": "/api/v1/countries", "method": "GET", "parameters": {"region": "string", "search": "string"}, "description": "전체 나라 목록 (region·search 쿼리로 필터 가능)"}, {"path": "/api/v1/countries/KR", "method": "GET", "parameters": {"code": "string"}, "description": "국가 코드(cca2/cca3)로 단건 조회. 경로의 KR을 원하는 코드로 바꾸세요 (예: KOR, US, JP)"}]'::jsonb, ARRAY['data','countries','geography','free','no-auth'], 'v1', true, false, NULL, 86400, NULL);

-- JSONPlaceholder  [data, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'JSONPlaceholder', '가짜 게시글, 댓글, 할일 목록, 사진 앨범 데이터. 연습용 또는 프로토타입 만들 때 유용해요.', 'data', 'https://jsonplaceholder.typicode.com', 'none', NULL, '500', true, 'https://jsonplaceholder.typicode.com/guide/', E'[{"path": "/posts", "method": "GET", "description": "게시글 목록", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=04e79764-c27c-46d8-b63c-2794fbe5a3f7&proxyPath=%2Fposts'');\\nconst items = await res.json(); // [{id, userId, title, body}]"}, {"path": "/todos", "method": "GET", "description": "할일 목록", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=04e79764-c27c-46d8-b63c-2794fbe5a3f7&proxyPath=%2Ftodos'');\\nconst items = await res.json(); // [{id, userId, title, completed}]"}, {"path": "/users", "method": "GET", "description": "사용자 목록", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=04e79764-c27c-46d8-b63c-2794fbe5a3f7&proxyPath=%2Fusers'');\\nconst items = await res.json(); // [{id, name, username, email}]"}]'::jsonb, ARRAY['data','mock','placeholder','free','no-auth'], 'v1', true, false, NULL, NULL, NULL);

-- Open Library  [data, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Open Library', '전 세계 도서 검색. 책 제목이나 저자로 검색하면 표지, 출판 정보를 알려줘요.', 'data', 'https://openlibrary.org', 'none', NULL, '100', true, 'https://openlibrary.org/developers/api', '[{"path": "/search.json", "method": "GET", "parameters": {"q": "string", "title": "string", "author": "string"}, "description": "도서 검색"}]'::jsonb, ARRAY['data','books','library','free','no-auth'], 'v1', true, false, NULL, NULL, NULL);

-- Random User  [data, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Random User', '가짜 사용자 프로필 자동 생성. 이름, 사진, 주소, 이메일 등 테스트 데이터를 만들 때 유용해요.', 'data', 'https://randomuser.me', 'none', NULL, '500', true, 'https://randomuser.me/documentation', E'[{"path": "/api/", "method": "GET", "parameters": {"nat": "string", "gender": "string", "results": "number"}, "description": "랜덤 사용자 프로필 생성", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=6890346f-fa79-483c-bce2-f841ad3420fd&proxyPath=%2Fapi%2F'');\\nconst data = await res.json();\\nconst items = data.results; // [{name, email, picture, location}]", "responseDataPath": "results"}]'::jsonb, ARRAY['data','users','mock','free','no-auth'], 'v1.4', true, false, NULL, NULL, NULL);

-- Wikipedia  [data, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Wikipedia', '위키피디아 문서 요약과 검색. 궁금한 것을 검색하면 짧은 요약문을 보여줘요. 한국어도 지원.', 'data', 'https://ko.wikipedia.org/api/rest_v1', 'none', NULL, '200', true, 'https://en.wikipedia.org/api/rest_v1/', '[{"path": "/page/summary/{title}", "method": "GET", "parameters": {"title": "string"}, "description": "문서 요약 조회"}, {"path": "/page/random/summary", "method": "GET", "description": "랜덤 문서 요약"}]'::jsonb, ARRAY['data','wikipedia','encyclopedia','free','no-auth'], 'v1', true, false, NULL, NULL, NULL);

-- REST Countries  [data, active=false, deprecated]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'REST Countries', '250개 나라의 수도, 인구, 국기, 언어, 통화 정보. 여행 준비나 세계 퀴즈 만들기에 딱!', 'data', 'https://restcountries.com', 'none', NULL, '500', false, 'https://restcountries.com/', '[{"path": "/v3.1/all", "method": "GET", "description": "전체 나라 목록"}, {"path": "/v3.1/name/{name}", "method": "GET", "parameters": {"name": "string"}, "description": "나라 이름으로 검색"}]'::jsonb, ARRAY['data','countries','geography','free','no-auth'], 'v3.1', true, false, NULL, NULL, '2026-06-21 11:50:39.804157+00'::timestamptz);

-- Open Trivia DB  [entertainment, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Open Trivia DB', '4,000개 이상 퀴즈 문제. 난이도와 카테고리를 골라서 퀴즈 게임을 만들 수 있어요.', 'entertainment', 'https://opentdb.com', 'none', NULL, '12/분(5초 간격)', true, 'https://opentdb.com/api_config.php', '[{"path": "/api.php", "method": "GET", "parameters": {"amount": "number", "category": "number", "difficulty": "string"}, "description": "퀴즈 문제 가져오기"}]'::jsonb, ARRAY['entertainment','trivia','quiz','free','no-auth'], 'v1', true, false, NULL, NULL, NULL);

-- PokéAPI  [entertainment, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'PokéAPI', '포켓몬 도감. 1,000마리 이상 포켓몬의 능력치, 타입, 이미지를 확인할 수 있어요.', 'entertainment', 'https://pokeapi.co', 'none', NULL, '300', true, 'https://pokeapi.co/docs/v2', E'[{"path": "/api/v2/pokemon/{id_or_name}", "method": "GET", "parameters": {"id_or_name": "string"}, "description": "포켓몬 상세 정보"}, {"path": "/api/v2/pokemon", "method": "GET", "parameters": {"limit": "number", "offset": "number"}, "description": "포켓몬 목록", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=02cea7ab-d89a-4e51-b9c5-32ed0fd00338&proxyPath=%2Fapi%2Fv2%2Fpokemon'');\\nconst data = await res.json();\\nconst items = data.results; // [{name, url}]", "responseDataPath": "results"}]'::jsonb, ARRAY['entertainment','pokemon','games','free','no-auth'], 'v2', true, false, NULL, NULL, NULL);

-- TheMealDB  [entertainment, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'TheMealDB', '전세계 레시피 데이터베이스. 랜덤 레시피, 검색, 카테고리별 필터 제공. ⚠️ 무료 키(v1/1)는 100건 이하·단일 재료 필터·기본 기능만 지원. v2 기능(랜덤 10개 등)은 Patreon 구독 키 필요.', 'entertainment', 'https://www.themealdb.com/api/json/v1/1', 'none', NULL, NULL, true, 'https://www.themealdb.com/api.php', E'[{"path": "/random.php", "method": "GET", "description": "랜덤 레시피 1개", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=<이 API ID>&proxyPath=%2Frandom.php'');\\nconst data = await res.json();\\nconst meal = data.meals[0]; // {strMeal, strCategory, strInstructions, strMealThumb}", "responseDataPath": "meals[0]"}, {"path": "/search.php", "method": "GET", "parameters": {"s": "요리명 (예: chicken)"}, "description": "레시피 검색", "responseDataPath": "meals"}, {"path": "/filter.php", "method": "GET", "parameters": {"c": "Chicken | Beef | Seafood | Vegetarian 등"}, "description": "카테고리별 레시피", "responseDataPath": "meals"}]'::jsonb, ARRAY['fun','food','recipe','cooking','free','no-auth'], NULL, true, false, NULL, NULL, NULL);

-- KOPIS 공연예술  [entertainment, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'KOPIS 공연예술', '공연예술통합전산망(KOPIS) 공연 정보. 공연 목록·상세·공연장 조회. XML 응답 (DOMParser 파싱 필요). (KOPIS 키 필요)', 'entertainment', 'https://www.kopis.or.kr/openApi/restful', 'api_key', '{"env_var": "API_KEY_KOPIS", "param_in": "query", "param_name": "service"}'::jsonb, '100', false, 'https://www.kopis.or.kr/por/cs/openapi/openApiUsageGuide.do', E'[{"path": "/pblprfr", "method": "GET", "parameters": {"rows": "10", "cpage": "1", "shcaf": "공연시설코드 (선택)", "shcat": "공연분야코드 (선택)", "eddate": "종료일 YYYYMMDD", "stdate": "시작일 YYYYMMDD", "shprfnm": "공연명 검색 (선택)"}, "description": "공연 목록 조회 (XML 반환)", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=<이 API ID>&proxyPath=%2Fpblprfr&stdate=20250501&eddate=20250531&cpage=1&rows=10'');\\nconst xml = await res.text();\\nconst parser = new DOMParser();\\nconst doc = parser.parseFromString(xml, ''text/xml'');\\nconst items = doc.querySelectorAll(''db'');", "responseDataPath": ""}, {"path": "/pblprfr/{mt20id}", "method": "GET", "parameters": {"mt20id": "공연 ID"}, "description": "공연 상세 정보 (XML 반환)", "responseDataPath": ""}]'::jsonb, ARRAY['entertainment','performance','culture','theater','kr','api_key','xml'], NULL, false, true, NULL, NULL, NULL);

-- RAWG  [entertainment, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'RAWG', '500,000개 이상 게임 데이터베이스. 인기 게임 목록, 검색, 상세정보 제공.', 'entertainment', 'https://api.rawg.io/api', 'api_key', '{"env_var": "API_KEY_RAWG", "param_in": "query", "param_name": "key"}'::jsonb, '20000/월', false, 'https://api.rawg.io/docs', E'[{"path": "/games", "method": "GET", "parameters": {"genres": "string (예: action,rpg)", "ordering": "-rating", "page_size": "20"}, "description": "게임 목록 조회", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=<이 API ID>&proxyPath=%2Fgames&page_size=20&ordering=-rating'');\\nconst data = await res.json();\\nconst games = data.results; // [{name, rating, background_image, genres}]", "responseDataPath": "results"}, {"path": "/games/{id}", "method": "GET", "parameters": {"id": "게임 ID 또는 slug"}, "description": "게임 상세 정보", "responseDataPath": ""}, {"path": "/genres", "method": "GET", "description": "장르 목록", "responseDataPath": "results"}]'::jsonb, ARRAY['entertainment','games','gaming','api_key'], NULL, true, false, NULL, NULL, NULL);

-- TMDB  [entertainment, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'TMDB', '영화·TV 데이터베이스. 인기 영화·드라마 목록, 검색, 상세정보 제공. 한국어(ko-KR) 지원.', 'entertainment', 'https://api.themoviedb.org/3', 'api_key', '{"env_var": "API_KEY_TMDB", "param_in": "query", "param_name": "api_key"}'::jsonb, NULL, false, 'https://developer.themoviedb.org/docs', E'[{"path": "/movie/popular", "method": "GET", "parameters": {"page": "1", "language": "ko-KR"}, "description": "인기 영화 목록", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=<이 API ID>&proxyPath=%2Fmovie%2Fpopular&language=ko-KR&page=1'');\\nconst data = await res.json();\\nconst movies = data.results;", "responseDataPath": "results"}, {"path": "/search/movie", "method": "GET", "parameters": {"query": "string", "language": "ko-KR"}, "description": "영화 검색", "responseDataPath": "results"}, {"path": "/tv/popular", "method": "GET", "parameters": {"language": "ko-KR"}, "description": "인기 TV 프로그램 목록", "responseDataPath": "results"}]'::jsonb, ARRAY['entertainment','movies','tv','film','api_key'], NULL, true, false, NULL, NULL, NULL);

-- ExchangeRate-API  [finance, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'ExchangeRate-API', '150개국 환율 조회. 가입 없이 바로 사용 가능해요. 원화(KRW) 포함 모든 통화 지원.', 'finance', 'https://open.er-api.com', 'none', NULL, '50', true, 'https://www.exchangerate-api.com/docs/free', '[{"path": "/v6/latest/{currency}", "method": "GET", "parameters": {"currency": "string"}, "description": "기준 통화 대비 전체 환율 조회"}]'::jsonb, ARRAY['finance','currency','exchange-rate','free','no-auth'], 'v6', true, false, NULL, NULL, NULL);

-- Frankfurter  [finance, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Frankfurter', '유럽중앙은행 기준 환율 조회. 30개국 통화를 실시간으로 변환할 수 있어요. 여행 환율 계산기에 딱!', 'finance', 'https://api.frankfurter.dev/v1', 'none', NULL, '300', true, 'https://frankfurter.dev', '[{"path": "/latest", "method": "GET", "parameters": {"to": "string", "from": "string"}, "description": "최신 환율 조회"}, {"path": "/{date}", "method": "GET", "parameters": {"date": "string"}, "description": "특정 날짜 환율 조회"}]'::jsonb, ARRAY['finance','currency','exchange-rate','free','no-auth'], 'v1', true, false, NULL, NULL, NULL);

-- 한국은행 경제통계 (ECOS)  [finance, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '한국은행 경제통계 (ECOS)', '한국은행 경제통계 API. GDP, 금리, 환율, 물가 등 거시 경제 지표 조회. 인증키 발급: data.go.kr이 아닌 ecos.bok.or.kr 자체 회원가입 필요.', 'finance', 'https://ecos.bok.or.kr/api', 'api_key', '{"env_var": "API_KEY_ECOS", "param_in": "path", "param_name": "authkey"}'::jsonb, '300', false, 'https://ecos.bok.or.kr/api/#/', '[{"path": "/StatisticSearch/{authkey}/json/kr/1/10/{statCode}", "method": "GET", "parameters": {"endDate": "string", "statCode": "string", "startDate": "string"}, "description": "통계 항목 조회"}]'::jsonb, ARRAY['finance','economy','korea','api-key'], 'v1', false, true, NULL, NULL, NULL);

-- icanhazdadjoke  [fun, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'icanhazdadjoke', '아재 개그 무한 생성기. 영어 유머 연습용으로도 좋아요. 매번 다른 개그가 나와요.', 'fun', 'https://icanhazdadjoke.com', 'none', NULL, '300', true, 'https://icanhazdadjoke.com/api', '[{"path": "/", "method": "GET", "description": "랜덤 아재 개그 (Accept: application/json 헤더 필요)"}]'::jsonb, ARRAY['fun','jokes','dad-jokes','free','no-auth'], 'v1', true, false, NULL, NULL, NULL);

-- JokeAPI  [fun, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'JokeAPI', '카테고리별 랜덤 유머. 프로그래밍 개그, 아재 개그 등 분위기 전환에 딱이에요.', 'fun', 'https://v2.jokeapi.dev', 'none', NULL, '120', true, 'https://jokeapi.dev/', '[{"path": "/joke/{category}", "method": "GET", "parameters": {"lang": "string", "type": "string", "category": "string"}, "description": "카테고리별 랜덤 유머 조회"}]'::jsonb, ARRAY['entertainment','jokes','humor','free','no-auth'], 'v2', true, false, NULL, NULL, NULL);

-- ZenQuotes  [fun, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'ZenQuotes', '명언·격언 랜덤 표시. 오늘의 한마디, 동기부여 화면을 만들 때 좋아요. HTTPS 지원, 무료, 인증 불필요.', 'fun', 'https://zenquotes.io/api', 'none', NULL, NULL, true, 'https://docs.zenquotes.io', E'[{"path": "/random", "method": "GET", "description": "랜덤 명언 1개 조회", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=4c6f5228-e6ec-45bb-b0bb-e947dcdeb1c1&proxyPath=%2Frandom'');\\nconst data = await res.json();\\nconst quote = data[0];\\n// quote.q (명언), quote.a (저자)", "responseDataPath": "[0]"}, {"path": "/quotes", "method": "GET", "description": "명언 50개 조회", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=4c6f5228-e6ec-45bb-b0bb-e947dcdeb1c1&proxyPath=%2Fquotes'');\\nconst data = await res.json();\\n// data: [{q: ''명언'', a: ''저자''}, ...]", "responseDataPath": ""}]'::jsonb, ARRAY['fun','quotes','inspiration','free','no-auth','https'], NULL, false, true, NULL, NULL, NULL);

-- HIRA 병원정보  [health, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'HIRA 병원정보', '건강보험심사평가원 병원·의원 정보 조회. 주소·진료과로 병원 검색. (공공데이터포털 키 필요)', 'health', 'https://apis.data.go.kr/B551182/hospInfoServicev2', 'api_key', '{"env_var": "API_KEY_HIRA", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '300', false, 'https://www.data.go.kr/data/15001698/openapi.do', E'[{"path": "/getHospBasisList", "method": "GET", "parameters": {"addr": "주소 (예: 서울특별시 강남구)", "type": "json", "pageNo": "1", "dgsbjtCd": "진료과코드 (예: 01=내과, 11=정형외과)", "numOfRows": "10"}, "description": "병원 기본 정보 목록", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=<이 API ID>&proxyPath=%2FgetHospBasisList&addr=서울특별시&pageNo=1&numOfRows=5&type=json'');\\nconst data = await res.json();\\nconst hospitals = data.response.body.items.item; // [{yadmNm, addr, telno, clCdNm}]", "responseDataPath": "response.body.items.item"}]'::jsonb, ARRAY['health','hospital','medical','kr','api_key','data.go.kr'], NULL, false, true, NULL, NULL, NULL);

-- 식약처 식품영양성분  [health, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '식약처 식품영양성분', '식품의약품안전처 식품 영양성분 데이터. 식품명으로 열량·단백질·지방·탄수화물 등 조회. (공공데이터포털 키 필요)', 'health', 'https://apis.data.go.kr/1471000/FoodNtrIrdntInfoService1', 'api_key', '{"env_var": "API_KEY_MFDS", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '300', false, 'https://www.data.go.kr/data/15100366/openapi.do', E'[{"path": "/getFoodNtrItdntList1", "method": "GET", "parameters": {"type": "json", "pageNo": "1", "desc_kor": "식품명 (한글)", "numOfRows": "10"}, "description": "식품 영양성분 목록 조회", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=<이 API ID>&proxyPath=%2FgetFoodNtrItdntList1&desc_kor=사과&pageNo=1&numOfRows=5&type=json'');\\nconst data = await res.json();\\nconst items = data.body.items;", "responseDataPath": "body.items"}]'::jsonb, ARRAY['health','food','nutrition','kr','api_key','data.go.kr'], NULL, false, true, NULL, NULL, NULL);

-- Dog API  [image, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Dog API', '120종 강아지 사진 20,000장. 품종별로 귀여운 강아지 사진을 볼 수 있어요.', 'image', 'https://dog.ceo', 'none', NULL, '300', true, 'https://dog.ceo/dog-api/', '[{"path": "/api/breeds/image/random", "method": "GET", "description": "랜덤 강아지 사진"}, {"path": "/api/breed/{breed}/images", "method": "GET", "parameters": {"breed": "string"}, "description": "품종별 사진 목록"}]'::jsonb, ARRAY['image','dogs','animals','free','no-auth'], 'v1', true, false, NULL, NULL, NULL);

-- Lorem Picsum  [image, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Lorem Picsum', '랜덤 고화질 사진 생성. URL에 크기만 넣으면 예쁜 사진이 나와요. 배경 이미지로 딱!', 'image', 'https://picsum.photos', 'none', NULL, '300', true, 'https://picsum.photos/', '[{"path": "/{width}/{height}", "method": "GET", "parameters": {"width": "number", "height": "number"}, "description": "지정 크기 랜덤 이미지"}, {"path": "/v2/list", "method": "GET", "description": "이미지 목록 조회"}]'::jsonb, ARRAY['image','placeholder','photos','free','no-auth'], 'v2', true, false, NULL, NULL, NULL);

-- NASA 오늘의 천문 사진  [image, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'NASA 오늘의 천문 사진', 'NASA가 매일 선정한 우주 사진 + 해설. DEMO_KEY로 가입 없이 바로 사용 가능해요.', 'image', 'https://api.nasa.gov', 'api_key', '{"env_var": "API_KEY_NASA", "param_in": "query", "param_name": "api_key", "default_key": "DEMO_KEY"}'::jsonb, '30', true, 'https://api.nasa.gov/', '[{"path": "/planetary/apod", "method": "GET", "parameters": {"date": "string", "api_key": "string"}, "description": "오늘의 천문 사진 조회"}]'::jsonb, ARRAY['image','space','nasa','astronomy','api-key'], 'v1', true, false, NULL, NULL, NULL);

-- The Cat API  [image, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'The Cat API', '랜덤 고양이 사진과 품종 정보. 집사라면 매일 다른 고양이 사진으로 힐링하세요.', 'image', 'https://api.thecatapi.com', 'none', NULL, '10/분', true, 'https://docs.thecatapi.com/', '[{"path": "/v1/images/search", "method": "GET", "parameters": {"limit": "number", "breed_ids": "string"}, "description": "랜덤 고양이 사진 검색"}]'::jsonb, ARRAY['image','cats','animals','api-key'], 'v1', true, false, NULL, NULL, NULL);

-- Unsplash  [image, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Unsplash', '전문 사진작가들의 고퀄리티 무료 사진 검색. 풍경, 음식, 사람 등 모든 주제를 검색할 수 있어요.', 'image', 'https://api.unsplash.com', 'api_key', '{"prefix": "Client-ID ", "env_var": "API_KEY_UNSPLASH", "param_in": "header", "param_name": "Authorization"}'::jsonb, '50/시간 (Demo) → 1000/시간 (Production 심사 후)', false, 'https://unsplash.com/documentation', '[{"path": "/photos/random", "method": "GET", "description": "랜덤 사진 조회"}, {"path": "/search/photos", "method": "GET", "parameters": {"query": "string"}, "description": "키워드 사진 검색"}]'::jsonb, ARRAY['image','photos','stock','api-key'], 'v1', true, false, NULL, NULL, NULL);

-- 공휴일 정보 (한국천문연구원)  [lifestyle, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '공휴일 정보 (한국천문연구원)', '대한민국 공휴일, 기념일, 24절기 정보. 달력 앱이나 D-day 계산기 만들 때 필수!', 'lifestyle', 'https://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService', 'api_key', '{"env_var": "API_KEY_15B51435", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '10000/일 (개발계정)', false, 'https://www.data.go.kr/data/15012690/openapi.do', '[{"path": "/getRestDeInfo", "method": "GET", "parameters": {"solYear": "string", "solMonth": "string"}, "description": "공휴일 조회"}]'::jsonb, ARRAY['lifestyle','holiday','calendar','korea','공공데이터','api-key'], 'v1', false, true, NULL, NULL, NULL);

-- 국립중앙도서관 도서 검색  [lifestyle, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '국립중앙도서관 도서 검색', '국내 도서 검색. 도서관 소장 여부, 서지 정보를 확인할 수 있어요. 책 읽기 좋아하는 분께 추천.', 'lifestyle', 'https://www.nl.go.kr/NL/search/openApi/search.do', 'api_key', '{"env_var": "API_KEY_83823C31", "param_in": "query", "param_name": "key"}'::jsonb, '300', false, 'https://www.nl.go.kr/NL/contents/N31101030700.do', '[{"path": "/sas498", "method": "GET", "parameters": {"kwd": "string"}, "description": "도서 검색"}]'::jsonb, ARRAY['lifestyle','books','library','korea','api-key'], 'v1', false, true, NULL, NULL, NULL);

-- 서울 열린데이터광장  [lifestyle, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '서울 열린데이터광장', '서울시 인구, 주차장, 문화행사, 와이파이 핫스팟 등 5,000개 데이터셋. 서울 생활에 유용한 정보 가득.', 'lifestyle', 'http://openapi.seoul.go.kr:8088', 'api_key', '{"env_var": "API_KEY_40037E2F", "param_in": "path", "param_name": "KEY"}'::jsonb, '300', false, 'https://data.seoul.go.kr/', '[{"path": "/{KEY}/json/{serviceName}/1/5/", "method": "GET", "parameters": {"serviceName": "string"}, "description": "서울시 공공데이터 조회"}]'::jsonb, ARRAY['lifestyle','seoul','opendata','korea','api-key'], 'v1', false, true, NULL, NULL, NULL);

-- 카카오 로컬 (지도·장소 검색)  [location, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '카카오 로컬 (지도·장소 검색)', '한국 주소 검색, 좌표 변환, 장소 검색. "강남역 맛집" 같은 키워드로 주변 장소를 찾을 수 있어요.', 'location', 'https://dapi.kakao.com', 'api_key', '{"prefix": "KakaoAK ", "env_var": "API_KEY_F1EC6F97", "param_in": "header", "param_name": "Authorization"}'::jsonb, '100000/일', false, 'https://developers.kakao.com/docs/latest/ko/local/dev-guide', '[{"path": "/v2/local/search/keyword.json", "method": "GET", "parameters": {"query": "string"}, "description": "키워드 장소 검색"}, {"path": "/v2/local/search/address.json", "method": "GET", "parameters": {"query": "string"}, "description": "주소 검색"}]'::jsonb, ARRAY['location','map','kakao','korea','api-key'], 'v2', true, false, NULL, NULL, NULL);

-- Hacker News API  [news, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Hacker News API', 'IT·스타트업 뉴스 실시간 조회. 실리콘밸리에서 가장 핫한 기술 소식을 모아볼 수 있어요.', 'news', 'https://hacker-news.firebaseio.com', 'none', NULL, '500', true, 'https://github.com/HackerNews/API', E'[{"path": "/v0/topstories.json", "method": "GET", "description": "인기 뉴스 ID 목록 (최대 500개)", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=de8f5375-22dc-4573-9a64-2903c150fece&proxyPath=%2Fv0%2Ftopstories.json'');\\nconst storyIds = await res.json(); // [integer IDs]"}, {"path": "/v0/item/{id}.json", "method": "GET", "parameters": {"id": "number"}, "description": "뉴스 상세 조회"}]'::jsonb, ARRAY['news','tech','hacker-news','free','no-auth'], 'v0', true, false, NULL, NULL, NULL);

-- Spaceflight News API  [news, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Spaceflight News API', '우주·항공 관련 뉴스 기사 검색. 로켓 발사, 우주 탐사 소식을 모아볼 수 있어요.', 'news', 'https://api.spaceflightnewsapi.net', 'none', NULL, '300', true, 'https://api.spaceflightnewsapi.net/v4/docs/', E'[{"path": "/v4/articles/", "method": "GET", "parameters": {"limit": "number", "search": "string"}, "description": "우주 뉴스 기사 목록", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=8461e4de-ba6d-4a4d-ae24-35bd7c47c0c7&proxyPath=%2Fv4%2Farticles%2F'');\\nconst data = await res.json();\\nconst items = data.results; // [{id, title, url, imageUrl, newsSite, summary, publishedAt}]", "responseDataPath": "results"}]'::jsonb, ARRAY['news','space','spaceflight','free','no-auth'], 'v4', true, false, NULL, NULL, NULL);

-- NEIS 학교급식  [public, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'NEIS 학교급식', '교육부 NEIS 학교 급식 식단 정보 API. 날짜·학교별 메뉴 조회. 무료 (교육행정정보시스템 키 필요).', 'public', 'https://open.neis.go.kr/hub', 'api_key', '{"env_var": "API_KEY_NEIS", "param_in": "query", "param_name": "KEY"}'::jsonb, '1000', false, 'https://open.neis.go.kr/portal/data/service/selectServicePage.do?page=1&rows=10&sortColumn=&sortDirection=&infId=OPEN17320190722180924242823&infSeq=2', E'[{"path": "/mealServiceDietInfo", "method": "GET", "parameters": {"Type": "json", "pSize": "10", "MLSV_YMD": "날짜 YYYYMMDD", "SD_SCHUL_CODE": "학교코드", "ATPT_OFCDC_SC_CODE": "시도교육청코드 (예: B10=서울)"}, "description": "학교 급식 식단 정보 조회", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=<이 API ID>&proxyPath=%2FmealServiceDietInfo&ATPT_OFCDC_SC_CODE=B10&SD_SCHUL_CODE=7010056&MLSV_YMD=20250501&Type=json&pSize=5'');\\nconst data = await res.json();\\nconst rows = data.mealServiceDietInfo[1].row;", "responseDataPath": "mealServiceDietInfo[1].row"}, {"path": "/schoolInfo", "method": "GET", "parameters": {"Type": "json", "pSize": "10", "SCHUL_NM": "학교명"}, "description": "학교 정보 조회 (학교명·코드 검색용)", "responseDataPath": "schoolInfo[1].row"}]'::jsonb, ARRAY['public','education','school','meal','kr','api_key'], NULL, false, true, NULL, NULL, NULL);

-- 국토부 아파트 전월세  [public, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '국토부 아파트 전월세', '국토교통부 아파트 전·월세 실거래 데이터. 지역코드·기간으로 임대 계약 내역 조회. (공공데이터포털 키 필요)', 'public', 'https://apis.data.go.kr/1613000/RTMSDataSvcAptRent', 'api_key', '{"env_var": "API_KEY_MOLIT", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '300', false, 'https://www.data.go.kr/data/15058017/openapi.do', E'[{"path": "/getRTMSDataSvcAptRent", "method": "GET", "parameters": {"pageNo": "1", "LAWD_CD": "법정동코드 앞 5자리 (예: 11680=강남구)", "DEAL_YMD": "계약연월 YYYYMM", "numOfRows": "10"}, "description": "아파트 전월세 실거래 조회", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=<이 API ID>&proxyPath=%2FgetRTMSDataSvcAptRent&LAWD_CD=11680&DEAL_YMD=202504&pageNo=1&numOfRows=10'');\\nconst data = await res.json();\\nconst items = data.response.body.items.item; // [{aptNm, deposit, monthlyRent, excluUseAr}]", "responseDataPath": "response.body.items.item"}]'::jsonb, ARRAY['public','real-estate','apartment','rent','kr','api_key','data.go.kr'], NULL, false, true, NULL, NULL, NULL);

-- 아파트 실거래가 (국토교통부)  [realestate, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '아파트 실거래가 (국토교통부)', '아파트 매매 실거래가 상세 자료. 지역코드·계약연월로 실거래 내역 조회. ℹ️ "Dev"는 개발/테스트용이 아닌 "상세 자료" 버전 정식 서비스명. (공공데이터포털 키 필요)', 'realestate', 'https://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev', 'api_key', '{"env_var": "API_KEY_BDA9BE95", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '10000/일 (개발계정)', false, 'https://www.data.go.kr/data/15126469/openapi.do', '[{"path": "/getRTMSDataSvcAptTradeDev", "method": "GET", "parameters": {"LAWD_CD": "string", "DEAL_YMD": "string"}, "description": "아파트 매매 실거래가 조회"}]'::jsonb, ARRAY['realestate','apartment','price','korea','공공데이터','api-key'], 'v1', false, true, NULL, NULL, NULL);

-- 카카오 검색  [search, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '카카오 검색', '카카오 REST API 검색 서비스. 웹·이미지·동영상·블로그·뉴스·도서 검색. 무료 (카카오 Developers REST API 키 필요).', 'search', 'https://dapi.kakao.com/v2', 'api_key', '{"env_var": "API_KEY_F1EC6F97", "param_in": "header", "param_name": "Authorization", "header_prefix": "KakaoAK "}'::jsonb, '50000/일', false, 'https://developers.kakao.com/docs/latest/ko/daum-search/dev-guide', E'[{"path": "/search/web", "method": "GET", "parameters": {"page": "1", "size": "10", "query": "검색어"}, "description": "웹 문서 검색", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=<이 API ID>&proxyPath=%2Fsearch%2Fweb&query=날씨&size=5'');\\nconst data = await res.json();\\nconst results = data.documents; // [{title, contents, url, datetime}]", "responseDataPath": "documents"}, {"path": "/search/image", "method": "GET", "parameters": {"size": "10", "query": "string"}, "description": "이미지 검색", "responseDataPath": "documents"}, {"path": "/search/book", "method": "GET", "parameters": {"size": "10", "query": "string"}, "description": "도서 검색", "responseDataPath": "documents"}]'::jsonb, ARRAY['search','kakao','web','image','book','kr','api_key'], NULL, true, false, NULL, NULL, NULL);

-- 한국관광공사 TourAPI  [tourism, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '한국관광공사 TourAPI', '전국 관광지, 맛집, 숙박, 축제 정보. 여행 계획 세울 때 지역별 볼거리·먹거리를 찾아보세요.', 'tourism', 'https://apis.data.go.kr/B551011/KorService1', 'api_key', '{"env_var": "API_KEY_TOURAPI", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '300', false, 'https://api.visitkorea.or.kr/', '[{"path": "/areaBasedList1", "method": "GET", "parameters": {"areaCode": "string", "contentTypeId": "string"}, "description": "지역 기반 관광지 목록"}, {"path": "/searchKeyword1", "method": "GET", "parameters": {"keyword": "string"}, "description": "키워드 검색"}]'::jsonb, ARRAY['tourism','travel','korea','공공데이터','api-key'], 'v1', false, true, NULL, NULL, NULL);

-- TAGO 전국 대중교통  [transport, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'TAGO 전국 대중교통', '전국 버스·지하철 노선/도착정보 API. 서비스별 경로 분리 (BusRouteInfoInqireService 등). 개발계정 10,000건/일. (공공데이터포털 키 필요)', 'transport', 'https://apis.data.go.kr/1613000', 'api_key', '{"env_var": "API_KEY_TAGO", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '300', false, 'https://www.data.go.kr/data/15098529/openapi.do', '[{"path": "/BusSttnInfoInqireService/getSttnNoList", "method": "GET", "parameters": {"sttnNm": "string"}, "description": "정류장 검색"}]'::jsonb, ARRAY['transport','bus','nationwide','korea','공공데이터','api-key'], 'v1', false, true, NULL, NULL, NULL);

-- 서울시 버스 도착정보  [transport, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '서울시 버스 도착정보', '서울 버스 실시간 도착 시간. 정류장 이름으로 검색하면 몇 분 후 버스가 오는지 알려줘요.', 'transport', 'http://ws.bus.go.kr/api/rest', 'api_key', '{"env_var": "API_KEY_4B98BB71", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '300', false, 'https://www.data.go.kr/data/15000314/openapi.do', '[{"path": "/arrive/getArrInfoByRouteAll", "method": "GET", "parameters": {"busRouteId": "string"}, "description": "노선별 도착 정보 조회"}]'::jsonb, ARRAY['transport','bus','seoul','korea','공공데이터','api-key'], 'v1', false, true, NULL, NULL, NULL);

-- 서울시 지하철 실시간 도착정보  [transport, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '서울시 지하철 실시간 도착정보', '서울 지하철 실시간 도착 예정 시간. 역 이름만 입력하면 다음 열차까지 남은 시간을 알려줘요.', 'transport', 'http://swopenAPI.seoul.go.kr/api/subway', 'api_key', '{"env_var": "API_KEY_70B9A73E", "param_in": "path", "param_name": "KEY"}'::jsonb, '300', false, 'https://data.seoul.go.kr/dataList/OA-12764/F/1/datasetView.do', '[{"path": "/{KEY}/json/realtimeStationArrival/0/5/{stationName}", "method": "GET", "parameters": {"stationName": "string"}, "description": "역별 실시간 도착 정보"}]'::jsonb, ARRAY['transport','subway','metro','seoul','korea','api-key'], 'v1', false, true, NULL, NULL, NULL);

-- QR Code Generator  [utility, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'QR Code Generator', '텍스트나 URL을 QR코드 이미지로 변환. 명함, 링크 공유에 유용해요.', 'utility', 'https://api.qrserver.com', 'none', NULL, '300', true, 'https://goqr.me/api/', '[{"path": "/v1/create-qr-code/", "method": "GET", "parameters": {"data": "string", "size": "string", "color": "string"}, "description": "QR코드 이미지 생성"}]'::jsonb, ARRAY['utility','qr-code','generator','free','no-auth'], 'v1', true, false, NULL, NULL, NULL);

-- Sunrise-Sunset  [utility, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Sunrise-Sunset', '원하는 위치의 일출·일몰 시각 조회. 캠핑, 낚시, 사진 촬영 계획 세울 때 유용해요.', 'utility', 'https://api.sunrise-sunset.org', 'none', NULL, '300', true, 'https://sunrise-sunset.org/api', '[{"path": "/json", "method": "GET", "parameters": {"lat": "number", "lng": "number", "date": "string"}, "description": "일출·일몰 시각 조회"}]'::jsonb, ARRAY['utility','sunrise','sunset','astronomy','free','no-auth'], 'v1', true, false, NULL, NULL, NULL);

-- The Color API  [utility, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'The Color API', 'HEX/RGB 색상 코드로 색상 이름·보완색·팔레트 생성. 인증 불필요.', 'utility', 'https://www.thecolorapi.com', 'none', NULL, NULL, true, 'https://www.thecolorapi.com/docs', E'[{"path": "/id", "method": "GET", "parameters": {"hex": "HEX 코드 (# 제외, 예: FF5733)"}, "description": "색상 정보 조회 (이름, RGB, HSL)", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=<이 API ID>&proxyPath=%2Fid&hex=FF5733'');\\nconst data = await res.json();\\n// data.name.value, data.rgb, data.hsl, data.image.bare", "responseDataPath": ""}, {"path": "/scheme", "method": "GET", "parameters": {"hex": "string", "mode": "monochrome | analogic | complement | triad | quad", "count": "5"}, "description": "색상 팔레트 생성", "responseDataPath": "colors"}]'::jsonb, ARRAY['utility','color','design','palette','free','no-auth'], NULL, true, false, NULL, NULL, NULL);

-- wheretheiss.at  [utility, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'wheretheiss.at', '국제우주정거장(ISS) 실시간 위치 추적. 위도·경도·고도·속도 제공. HTTPS 지원, 무료.', 'utility', 'https://api.wheretheiss.at', 'none', NULL, '60', true, 'https://wheretheiss.at/w/developer', E'[{"path": "/v1/satellites/25544", "method": "GET", "description": "ISS 현재 위치 (위도·경도·고도·속도)", "exampleCall": "const res = await fetch(''/api/v1/proxy?apiId=9a04cd18-15bb-4424-a4f1-10ddf728749b&proxyPath=%2Fv1%2Fsatellites%2F25544'');\\nconst data = await res.json();\\n// data.latitude, data.longitude, data.altitude, data.velocity", "responseDataPath": ""}, {"path": "/v1/satellites", "method": "GET", "description": "추적 가능 위성 목록"}]'::jsonb, ARRAY['utility','space','iss','satellite','free','no-auth','https'], 'v1', false, true, NULL, NULL, NULL);

-- Open-Meteo  [weather, active=true]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'Open-Meteo', '무료 날씨 API. 키 불필요, 비상업적 전용(CC BY 4.0). 위도/경도 기반 현재 날씨 및 예보 제공.', 'weather', 'https://api.open-meteo.com', 'none', NULL, '10000/일', true, 'https://open-meteo.com/en/docs', '[{"path": "/v1/forecast", "method": "GET", "description": "위도/경도 기반 날씨 예보", "example_call": "/v1/forecast?latitude=37.5665&longitude=126.9780&current_weather=true"}]'::jsonb, ARRAY['weather','forecast','free','no-key'], NULL, true, false, NULL, NULL, NULL);

-- OpenWeatherMap  [weather, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'OpenWeatherMap', '현재 날씨, 5일 예보, 대기질 정보를 제공해요. 무료 가입 후 API 키를 발급받아 사용합니다.', 'weather', 'https://api.openweathermap.org', 'api_key', '{"env_var": "API_KEY_OPENWEATHERMAP", "param_in": "query", "param_name": "appid"}'::jsonb, '60', false, 'https://openweathermap.org/api', '[{"path": "/data/2.5/weather", "method": "GET", "parameters": {"q": "string", "lat": "number", "lon": "number", "units": "string"}, "description": "도시명 또는 좌표로 현재 날씨 조회"}]'::jsonb, ARRAY['weather','forecast','api-key'], 'v2.5', true, false, 0, NULL, NULL);

-- WeatherAPI.com  [weather, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  'WeatherAPI.com', '14일 예보 + 일출·일몰 시각을 알려줘요. 월 100만 호출 무료. 캠핑·야외 활동 계획에 유용합니다.', 'weather', 'https://api.weatherapi.com', 'api_key', '{"env_var": "API_KEY_WEATHERAPICOM", "param_in": "query", "param_name": "key"}'::jsonb, '100000/월', false, 'https://www.weatherapi.com/docs/', '[{"path": "/v1/forecast.json", "method": "GET", "parameters": {"q": "string", "days": "number"}, "description": "날씨 예보 조회 (최대 14일)"}]'::jsonb, ARRAY['weather','forecast','astronomy','api-key'], 'v1', true, false, NULL, NULL, NULL);

-- 기상청 단기예보  [weather, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '기상청 단기예보', '우리 동네 날씨 예보. 기온, 비, 눈, 바람, 습도를 3시간 단위로 알려줘요. 공공데이터포털 무료 가입 후 사용.', 'weather', 'https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0', 'api_key', '{"env_var": "API_KEY_7CB8F428", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '10000/일 (개발계정)', false, 'https://www.data.go.kr/data/15084084/openapi.do', '[{"path": "/getVilageFcst", "method": "GET", "parameters": {"nx": "number", "ny": "number", "base_date": "string", "base_time": "string"}, "description": "동네 예보 조회 (3시간 단위)"}]'::jsonb, ARRAY['weather','korea','공공데이터','api-key'], 'v2.0', false, true, NULL, 10800, NULL);

-- 기상청 중기예보  [weather, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '기상청 중기예보', '3~10일 후 날씨 전망. 이번 주 비가 올지, 기온이 어떨지 미리 확인할 수 있어요.', 'weather', 'https://apis.data.go.kr/1360000/MidFcstInfoService', 'api_key', '{"env_var": "API_KEY_00412C2B", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '10000/일 (개발계정)', false, 'https://www.data.go.kr/data/15059468/openapi.do', '[{"path": "/getMidTa", "method": "GET", "parameters": {"tmFc": "string", "regId": "string"}, "description": "중기 기온 예보 조회"}]'::jsonb, ARRAY['weather','korea','공공데이터','api-key'], 'v1', false, true, NULL, 21600, NULL);

-- 에어코리아 대기오염정보  [weather, active=false]
INSERT INTO api_catalog (name, description, category, base_url, auth_type, auth_config, rate_limit, is_active, docs_url, endpoints, tags, api_version, cors_supported, requires_proxy, credit_required, cache_ttl_seconds, deprecated_at) VALUES (
  '에어코리아 대기오염정보', '대기오염 측정 정보. 측정소별 미세먼지·초미세먼지·오존 등 실시간 조회. ⚠️ 개발계정 일일 한도 500건 (타 공공API 10,000건의 1/20). (공공데이터포털 키 필요)', 'weather', 'https://apis.data.go.kr/B552584/ArpltnInforInqireSvc', 'api_key', '{"env_var": "API_KEY_C84860A1", "param_in": "query", "param_name": "serviceKey"}'::jsonb, '500/일', false, 'https://www.data.go.kr/data/15073861/openapi.do', '[{"path": "/getMsrstnAcctoRltmMesureDnsty", "method": "GET", "parameters": {"dataTerm": "string", "stationName": "string"}, "description": "측정소별 실시간 대기질 조회"}]'::jsonb, ARRAY['weather','air-quality','korea','공공데이터','api-key'], 'v1', false, true, NULL, NULL, NULL);

-- ============================================================
-- 폐기 API 후속(successor) 연결
-- ============================================================
-- successor_id는 생성된 UUID이므로 이름 기준으로 연결한다.
-- REST Countries(폐기) → Countries (Self-hosted) 대체.
UPDATE api_catalog
SET successor_id = (SELECT id FROM api_catalog WHERE name = 'Countries (Self-hosted)')
WHERE name = 'REST Countries';
