export const CATEGORY_LABELS: Record<string, string> = {
  weather: '날씨/환경',
  news: '뉴스',
  finance: '금융/환율',
  maps: '지도/위치',
  location: '지도/위치',
  translation: '번역/언어',
  dictionary: '사전/번역',
  image: '이미지',
  data: '데이터/정보',
  utility: '유틸리티',
  entertainment: '엔터테인먼트',
  fun: '재미/이름분석',
  social: '소셜',
  transport: '교통',
  realestate: '부동산',
  tourism: '관광/여행',
  lifestyle: '생활/공공',
  science: '과학/우주',
};

export const CATEGORY_ICONS: Record<string, string> = {
  weather: 'Cloud',
  news: 'Newspaper',
  finance: 'DollarSign',
  maps: 'MapPin',
  location: 'MapPin',
  translation: 'Languages',
  dictionary: 'BookOpen',
  image: 'Image',
  data: 'Database',
  utility: 'Wrench',
  entertainment: 'Film',
  fun: 'Smile',
  social: 'Users',
  transport: 'Bus',
  realestate: 'Building',
  tourism: 'Compass',
  lifestyle: 'Heart',
  science: 'Telescope',
};
